<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="账户管理测试"
           tests="11"
           failures="1"
           errors="0"
           skipped="0"
           time="1179.895">
  <properties />
            <testcase name="testRiskEvaluation" time="86.394" classname="com.hjs.cases.AccountManageTestCase">
                <failure type="java.lang.AssertionError"
                  message="实际风评结果为成长型然而期待结果为进取型 expected [进取型] but found [成长型]"
              >
<![CDATA[java.lang.AssertionError: 实际风评结果为成长型然而期待结果为进取型 expected [进取型] but found [成长型]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  com.hjs.cases.AccountManageTestCase.testRiskEvaluation(AccountManageTestCase.java:221)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testResetTradePwd" time="207.357" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testReRiskEvaluation" time="126.031" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testWelcomePage" time="16.185" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testGesturePwd" time="32.954" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testRealNameAndSetBankCard" time="260.616" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testSignedPhoneLogin" time="67.835" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testSignAccount" time="203.153" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testUnBundBankCard" time="86.111" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testResetLoginPwd" time="74.202" classname="com.hjs.cases.AccountManageTestCase" />
                <testcase name="testLogOut" time="19.057" classname="com.hjs.cases.AccountManageTestCase" />
      
</testsuite>
